version: "3.8"

services:
  test_database:
    image: postgres
    container_name: test_database
    restart: always
    ports:
      - 8080:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx_test
    volumes:
      - pgdata:/test_data/postgres
      
volumes:
  pgdata:
    driver: local